---
title: "Making locally relevant stories using PPP loans and scripting"
author: "Matt Waite"
date: 2020-07-07T12:27:00-05:00
categories: ["projects"]
tags: ["coronavirus", "automation"]
banner: "img/banners/generic.png"
description: "How we used R, the tidyverse and PPP Loan data to make locally relevant stories for 252 communities"
---

On Monday, the Small Business Administration released the names of some 650,000 Paycheck Protection Program loans given to businesses during the pandemic. Big news organizations went into action, [finding the politcally connected who got loans](https://www.propublica.org/article/trump-friends-and-family-cleared-for-millions-in-small-business-bailout), [interesting businesses who got them](https://apnews.com/8798e58a0ddc490ad549329b343e551c) and [even some irony in the data](https://www.reuters.com/article/us-health-coronavirus-ppp-ayn-rand/in-sign-of-the-times-ayn-rand-institute-approved-for-ppp-loan-idUSKBN248026).

But for very small organizations, who don't have data desks and investigative units, the data wasn't particularly useful. For small town newspapers, local companies getting PPP loans is an interesting story, but most of them lack the resources to go diving into a 127 MB spreadsheet. 

This is the kind of story the Roper Lab for Data in Community News was created for. We can be the data desk for those who don't have one. 

What we did in this case was take the data and create 253 stories, one for each town that had a company that got a loan. We used the data to write a locally relevant headline and top to the story, six paragraphs of context, and then for each town, we included a list of companies who got loans and what range of loan they got (the SBA did not report exact figures). 

The main clients of the Roper Data Lab are members of the [Nebraska News Service](https://nebraskanewsservice.net/) at the University of Nebraska-Lincoln's College of Journalism and Mass Communications. More than 100 news organizations in the state, from small town newspapers to community radio stations to local television, receive News Service stories for free via email. They can range from tiny organizations with just a few employees to daily newspapers in some of the larger towns in the state. 

So our target was to get locally relevant stories into their hands. To do this, we used R to clean up the data, query interesting information about Nebraska companies, and then write unique stories for each city where a company that got a loan is based. At the end of each story is a list of companies in that town who got a loan.

The code also converts numbers into AP Style, switches pluralization of business and changes the verb is/are where needed automatically to create clean copy. It also conditionally adds context when companies don't report the number of jobs they believed they would retain with the money. 

In all, our code wrote 253 stories, but there's dozens of variations of the story within those 253. Here's an example from my hometown of Blair, Nebraska.

> SBA: 35 Blair businesses got pandemic loans
>
>The Small Business Administration on Monday released some details about 4,179 Nebraska businesses that took out Paycheck Protection Program loans of $150,000 or more.
>
>Of them, 35 are from Blair and the businesses planned in their loan paperwork to preserve 1,386 jobs with that money. However, three did not report information about jobs preserved with the loan.
>
>The data released by the Small Business Administration on Monday is only a small slice of all Paycheck Protection loans issued during the pandemic. The government revealed details of 650,000 loans on Monday. In all, more than 5 million loans were granted under the program.
>
>The loans are low-interest loans that can be forgiven if the company uses the money to retain employees. Companies are just now beginning the loan forgiveness process.
>
>Statewide, Omaha had the most loans at 1,598, which represented 38 percent of all loans given to Nebraska businesses. Lincoln (672), Grand Island, (147), Kearney (116) and Norfolk (89) rounded out the top 5.
>
>The Small Business Administration did not report the exact amount each business took out in loans, offering a range that the loan fell into. Only loans of $150,000 or more were reported.
>
>Of the 4,179 loans, 2,394 of them were for the lowest range, $150,000 to $350,000. Statewide, 36 businesses got loans of $5 million to $10 million.
>
>Among those top loan amount recipients are variety of businesses, mostly based in eastern Nebraska. Several are medical companies, such as the Kearney Regional Medical Center and the Nebraska Orthopaedic Hospital in Omaha. Rotella's Italian Bakery claimed to have retained 466 jobs with their upper range loan. Several agriculture industry businesses also topped the list.
>
>Sixteen business reported that they would retain 500 jobs with their loans, the highest amount disclosed by federal regulators.
>
>The average number of jobs preserved by companies who reported that number is 51. However, 106 Nebraska companies said they retained zero workers with the loan. Another 644 left the question blank on their application.

The list of companies include my dentist growing up, the town mortuary, the elderly care home my grandmother lived in before she passed, the company that will replace the roof on my house soon, the two big car dealers in town and ... the local newspaper. 

Those stories were sent to news service clients in a Box folder, where they could find a story named for each town. As of this writing, we don't know how many will use the stories -- weekly and twice weekly publication schedules and all.

Our code, like every story we do in the Roper Lab, [is public and online](https://github.com/RoperDataLab/PPPloans). You can see what we did yourself. 
