---
title: "Help us tell the stories of Nebraskans who have died of coronavirus"
author: "Will Bauer"
date: 2020-06-24T11:27:00-05:00
categories: ["projects"]
tags: ["coronavirus", "crowdsourcing"]
banner: "img/banners/generic.png"
description: "We're trying to help Nebraskans remember those who have died from COVID-19. Can you help?"
---

More than 250 Nebraskan's have died during the pandemic, but we don't know much about them. Every day, a health department in the state issues a press release that says a man or a woman of such and such age died. 

But no more. 

These people are mothers and fathers, brothers and sisters, friends, neighbors, members of our community. And we know so little about them. 

In any other time, we would have memorials to the dead. What we're attempting to do is to fix that. We want to help Nebraska remember those lost to COVID-19. And we need your help.

We would like to create a list of everyone we've lost. Their name. Where they're from. A little bit about them. Ideally, we'd like to talk to people who know them and can tell us more. We're collecting this information for news organizations around the state so communities can remember their neighbors. 

Do you know someone? [Fill this form out and let us know](https://docs.google.com/forms/d/e/1FAIpQLSc3XEanHuV8wi6hRdqbPXO1QCvR0zQ1vzr4osGI9LT0f2NEAg/viewform?usp=sf_link).
